<?php

// [country, ISO 4217 code, symbol] — used to populate the currency picker
// in Business Profile settings and to resolve a gym's display symbol.
return [
    ['country' => 'Afghanistan', 'code' => 'AFN', 'symbol' => '؋'],
    ['country' => 'Albania', 'code' => 'ALL', 'symbol' => 'L'],
    ['country' => 'Algeria', 'code' => 'DZD', 'symbol' => 'د.ج'],
    ['country' => 'Andorra', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Angola', 'code' => 'AOA', 'symbol' => 'Kz'],
    ['country' => 'Argentina', 'code' => 'ARS', 'symbol' => '$'],
    ['country' => 'Armenia', 'code' => 'AMD', 'symbol' => '֏'],
    ['country' => 'Australia', 'code' => 'AUD', 'symbol' => '$'],
    ['country' => 'Austria', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Azerbaijan', 'code' => 'AZN', 'symbol' => '₼'],
    ['country' => 'Bahamas', 'code' => 'BSD', 'symbol' => '$'],
    ['country' => 'Bahrain', 'code' => 'BHD', 'symbol' => '.د.ب'],
    ['country' => 'Bangladesh', 'code' => 'BDT', 'symbol' => '৳'],
    ['country' => 'Barbados', 'code' => 'BBD', 'symbol' => '$'],
    ['country' => 'Belarus', 'code' => 'BYN', 'symbol' => 'Br'],
    ['country' => 'Belgium', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Belize', 'code' => 'BZD', 'symbol' => '$'],
    ['country' => 'Benin', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Bhutan', 'code' => 'BTN', 'symbol' => 'Nu.'],
    ['country' => 'Bolivia', 'code' => 'BOB', 'symbol' => 'Bs.'],
    ['country' => 'Bosnia and Herzegovina', 'code' => 'BAM', 'symbol' => 'KM'],
    ['country' => 'Botswana', 'code' => 'BWP', 'symbol' => 'P'],
    ['country' => 'Brazil', 'code' => 'BRL', 'symbol' => 'R$'],
    ['country' => 'Brunei', 'code' => 'BND', 'symbol' => '$'],
    ['country' => 'Bulgaria', 'code' => 'BGN', 'symbol' => 'лв'],
    ['country' => 'Burkina Faso', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Burundi', 'code' => 'BIF', 'symbol' => 'Fr'],
    ['country' => 'Cambodia', 'code' => 'KHR', 'symbol' => '៛'],
    ['country' => 'Cameroon', 'code' => 'XAF', 'symbol' => 'Fr'],
    ['country' => 'Canada', 'code' => 'CAD', 'symbol' => '$'],
    ['country' => 'Cape Verde', 'code' => 'CVE', 'symbol' => '$'],
    ['country' => 'Central African Republic', 'code' => 'XAF', 'symbol' => 'Fr'],
    ['country' => 'Chad', 'code' => 'XAF', 'symbol' => 'Fr'],
    ['country' => 'Chile', 'code' => 'CLP', 'symbol' => '$'],
    ['country' => 'China', 'code' => 'CNY', 'symbol' => '¥'],
    ['country' => 'Colombia', 'code' => 'COP', 'symbol' => '$'],
    ['country' => 'Comoros', 'code' => 'KMF', 'symbol' => 'Fr'],
    ['country' => 'Congo (DRC)', 'code' => 'CDF', 'symbol' => 'Fr'],
    ['country' => 'Congo (Republic)', 'code' => 'XAF', 'symbol' => 'Fr'],
    ['country' => 'Costa Rica', 'code' => 'CRC', 'symbol' => '₡'],
    ['country' => 'Croatia', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Cuba', 'code' => 'CUP', 'symbol' => '$'],
    ['country' => 'Cyprus', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Czech Republic', 'code' => 'CZK', 'symbol' => 'Kč'],
    ['country' => 'Denmark', 'code' => 'DKK', 'symbol' => 'kr'],
    ['country' => 'Djibouti', 'code' => 'DJF', 'symbol' => 'Fr'],
    ['country' => 'Dominican Republic', 'code' => 'DOP', 'symbol' => 'RD$'],
    ['country' => 'Ecuador', 'code' => 'USD', 'symbol' => '$'],
    ['country' => 'Egypt', 'code' => 'EGP', 'symbol' => '£'],
    ['country' => 'El Salvador', 'code' => 'USD', 'symbol' => '$'],
    ['country' => 'Equatorial Guinea', 'code' => 'XAF', 'symbol' => 'Fr'],
    ['country' => 'Eritrea', 'code' => 'ERN', 'symbol' => 'Nfk'],
    ['country' => 'Estonia', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Eswatini', 'code' => 'SZL', 'symbol' => 'L'],
    ['country' => 'Ethiopia', 'code' => 'ETB', 'symbol' => 'Br'],
    ['country' => 'Fiji', 'code' => 'FJD', 'symbol' => '$'],
    ['country' => 'Finland', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'France', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Gabon', 'code' => 'XAF', 'symbol' => 'Fr'],
    ['country' => 'Gambia', 'code' => 'GMD', 'symbol' => 'D'],
    ['country' => 'Georgia', 'code' => 'GEL', 'symbol' => '₾'],
    ['country' => 'Germany', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Ghana', 'code' => 'GHS', 'symbol' => '₵'],
    ['country' => 'Greece', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Guatemala', 'code' => 'GTQ', 'symbol' => 'Q'],
    ['country' => 'Guinea', 'code' => 'GNF', 'symbol' => 'Fr'],
    ['country' => 'Guyana', 'code' => 'GYD', 'symbol' => '$'],
    ['country' => 'Haiti', 'code' => 'HTG', 'symbol' => 'G'],
    ['country' => 'Honduras', 'code' => 'HNL', 'symbol' => 'L'],
    ['country' => 'Hong Kong', 'code' => 'HKD', 'symbol' => '$'],
    ['country' => 'Hungary', 'code' => 'HUF', 'symbol' => 'Ft'],
    ['country' => 'Iceland', 'code' => 'ISK', 'symbol' => 'kr'],
    ['country' => 'India', 'code' => 'INR', 'symbol' => '₹'],
    ['country' => 'Indonesia', 'code' => 'IDR', 'symbol' => 'Rp'],
    ['country' => 'Iran', 'code' => 'IRR', 'symbol' => '﷼'],
    ['country' => 'Iraq', 'code' => 'IQD', 'symbol' => 'ع.د'],
    ['country' => 'Ireland', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Israel', 'code' => 'ILS', 'symbol' => '₪'],
    ['country' => 'Italy', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Ivory Coast', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Jamaica', 'code' => 'JMD', 'symbol' => '$'],
    ['country' => 'Japan', 'code' => 'JPY', 'symbol' => '¥'],
    ['country' => 'Jordan', 'code' => 'JOD', 'symbol' => 'د.ا'],
    ['country' => 'Kazakhstan', 'code' => 'KZT', 'symbol' => '₸'],
    ['country' => 'Kenya', 'code' => 'KES', 'symbol' => 'KSh'],
    ['country' => 'Kuwait', 'code' => 'KWD', 'symbol' => 'د.ك'],
    ['country' => 'Kyrgyzstan', 'code' => 'KGS', 'symbol' => 'с'],
    ['country' => 'Laos', 'code' => 'LAK', 'symbol' => '₭'],
    ['country' => 'Latvia', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Lebanon', 'code' => 'LBP', 'symbol' => 'ل.ل'],
    ['country' => 'Lesotho', 'code' => 'LSL', 'symbol' => 'L'],
    ['country' => 'Liberia', 'code' => 'LRD', 'symbol' => '$'],
    ['country' => 'Libya', 'code' => 'LYD', 'symbol' => 'ل.د'],
    ['country' => 'Liechtenstein', 'code' => 'CHF', 'symbol' => 'Fr'],
    ['country' => 'Lithuania', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Luxembourg', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Madagascar', 'code' => 'MGA', 'symbol' => 'Ar'],
    ['country' => 'Malawi', 'code' => 'MWK', 'symbol' => 'MK'],
    ['country' => 'Malaysia', 'code' => 'MYR', 'symbol' => 'RM'],
    ['country' => 'Maldives', 'code' => 'MVR', 'symbol' => '.ރ'],
    ['country' => 'Mali', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Malta', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Mauritania', 'code' => 'MRU', 'symbol' => 'UM'],
    ['country' => 'Mauritius', 'code' => 'MUR', 'symbol' => '₨'],
    ['country' => 'Mexico', 'code' => 'MXN', 'symbol' => '$'],
    ['country' => 'Moldova', 'code' => 'MDL', 'symbol' => 'L'],
    ['country' => 'Monaco', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Mongolia', 'code' => 'MNT', 'symbol' => '₮'],
    ['country' => 'Montenegro', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Morocco', 'code' => 'MAD', 'symbol' => 'د.م.'],
    ['country' => 'Mozambique', 'code' => 'MZN', 'symbol' => 'MT'],
    ['country' => 'Myanmar', 'code' => 'MMK', 'symbol' => 'K'],
    ['country' => 'Namibia', 'code' => 'NAD', 'symbol' => '$'],
    ['country' => 'Nepal', 'code' => 'NPR', 'symbol' => '₨'],
    ['country' => 'Netherlands', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'New Zealand', 'code' => 'NZD', 'symbol' => '$'],
    ['country' => 'Nicaragua', 'code' => 'NIO', 'symbol' => 'C$'],
    ['country' => 'Niger', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Nigeria', 'code' => 'NGN', 'symbol' => '₦'],
    ['country' => 'North Macedonia', 'code' => 'MKD', 'symbol' => 'ден'],
    ['country' => 'Norway', 'code' => 'NOK', 'symbol' => 'kr'],
    ['country' => 'Oman', 'code' => 'OMR', 'symbol' => 'ر.ع.'],
    ['country' => 'Pakistan', 'code' => 'PKR', 'symbol' => '₨'],
    ['country' => 'Panama', 'code' => 'PAB', 'symbol' => 'B/.'],
    ['country' => 'Papua New Guinea', 'code' => 'PGK', 'symbol' => 'K'],
    ['country' => 'Paraguay', 'code' => 'PYG', 'symbol' => '₲'],
    ['country' => 'Peru', 'code' => 'PEN', 'symbol' => 'S/'],
    ['country' => 'Philippines', 'code' => 'PHP', 'symbol' => '₱'],
    ['country' => 'Poland', 'code' => 'PLN', 'symbol' => 'zł'],
    ['country' => 'Portugal', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Qatar', 'code' => 'QAR', 'symbol' => 'ر.ق'],
    ['country' => 'Romania', 'code' => 'RON', 'symbol' => 'lei'],
    ['country' => 'Russia', 'code' => 'RUB', 'symbol' => '₽'],
    ['country' => 'Rwanda', 'code' => 'RWF', 'symbol' => 'Fr'],
    ['country' => 'Saudi Arabia', 'code' => 'SAR', 'symbol' => '﷼'],
    ['country' => 'Senegal', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Serbia', 'code' => 'RSD', 'symbol' => 'дин.'],
    ['country' => 'Seychelles', 'code' => 'SCR', 'symbol' => '₨'],
    ['country' => 'Sierra Leone', 'code' => 'SLE', 'symbol' => 'Le'],
    ['country' => 'Singapore', 'code' => 'SGD', 'symbol' => '$'],
    ['country' => 'Slovakia', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Slovenia', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Somalia', 'code' => 'SOS', 'symbol' => 'Sh'],
    ['country' => 'South Africa', 'code' => 'ZAR', 'symbol' => 'R'],
    ['country' => 'South Korea', 'code' => 'KRW', 'symbol' => '₩'],
    ['country' => 'South Sudan', 'code' => 'SSP', 'symbol' => '£'],
    ['country' => 'Spain', 'code' => 'EUR', 'symbol' => '€'],
    ['country' => 'Sri Lanka', 'code' => 'LKR', 'symbol' => '₨'],
    ['country' => 'Sudan', 'code' => 'SDG', 'symbol' => 'ج.س.'],
    ['country' => 'Suriname', 'code' => 'SRD', 'symbol' => '$'],
    ['country' => 'Sweden', 'code' => 'SEK', 'symbol' => 'kr'],
    ['country' => 'Switzerland', 'code' => 'CHF', 'symbol' => 'Fr'],
    ['country' => 'Syria', 'code' => 'SYP', 'symbol' => 'ل.س'],
    ['country' => 'Taiwan', 'code' => 'TWD', 'symbol' => 'NT$'],
    ['country' => 'Tajikistan', 'code' => 'TJS', 'symbol' => 'ЅМ'],
    ['country' => 'Tanzania', 'code' => 'TZS', 'symbol' => 'Sh'],
    ['country' => 'Thailand', 'code' => 'THB', 'symbol' => '฿'],
    ['country' => 'Togo', 'code' => 'XOF', 'symbol' => 'Fr'],
    ['country' => 'Trinidad and Tobago', 'code' => 'TTD', 'symbol' => '$'],
    ['country' => 'Tunisia', 'code' => 'TND', 'symbol' => 'د.ت'],
    ['country' => 'Turkey', 'code' => 'TRY', 'symbol' => '₺'],
    ['country' => 'Turkmenistan', 'code' => 'TMT', 'symbol' => 'm'],
    ['country' => 'Uganda', 'code' => 'UGX', 'symbol' => 'Sh'],
    ['country' => 'Ukraine', 'code' => 'UAH', 'symbol' => '₴'],
    ['country' => 'United Arab Emirates', 'code' => 'AED', 'symbol' => 'د.إ'],
    ['country' => 'United Kingdom', 'code' => 'GBP', 'symbol' => '£'],
    ['country' => 'United States', 'code' => 'USD', 'symbol' => '$'],
    ['country' => 'Uruguay', 'code' => 'UYU', 'symbol' => '$'],
    ['country' => 'Uzbekistan', 'code' => 'UZS', 'symbol' => "so'm"],
    ['country' => 'Vanuatu', 'code' => 'VUV', 'symbol' => 'Vt'],
    ['country' => 'Venezuela', 'code' => 'VES', 'symbol' => 'Bs.'],
    ['country' => 'Vietnam', 'code' => 'VND', 'symbol' => '₫'],
    ['country' => 'Yemen', 'code' => 'YER', 'symbol' => '﷼'],
    ['country' => 'Zambia', 'code' => 'ZMW', 'symbol' => 'ZK'],
    ['country' => 'Zimbabwe', 'code' => 'ZWL', 'symbol' => '$'],
];
